---
- hosts: all
  vars:
    current_user: "{{ lookup('env', 'USER') }}"
    home_dir: "{{ lookup('env', 'HOME') }}"
  roles:
    - { role: git, tags: ['git'] }
    - { role: ssh, tags: ['ssh'] }
    - { role: nvim, tags: ['nvim'] }
    - { role: bash, tags: ['bash'] }
    - { role: terraform, tags: ['terraform'] }
    - { role: brew, tags: ['brew'] }
