---
- hosts: all
  vars:
    current_user: "{{ lookup('env', 'USER') }}"
    home_dir: "{{ lookup('env', 'HOME') }}"
  pre_tasks:
    - name: get installed applications
      command:
        cmd: "ls -la /Applications/"
      register: installed_applications
      tags:
        - always
  roles:
    - { role: git, tags: ['git'] }
    - { role: ssh, tags: ['ssh'] }
    - { role: nvim, tags: ['nvim'] }
    - { role: bash, tags: ['bash'] }
    - { role: terraform, tags: ['terraform'] }
    - { role: brew, tags: ['brew'] }
    - { role: docker, tags: ['docker'] }
    - { role: azurecli, tags: ['azurecli'] }
    - { role: vscode, tags: ['vscode'] }
    - { role: helm, tags: ['helm'] }
    - { role: go, tags: ['go'] }
    - { role: awscli, tags: ['aws'] }
