---

# NOTE: brew install is done because ansible is trying to run brew cask when it should be brew install --cask 
- name: install docker
  command:
    cmd: brew install --cask docker
  when: not "'Docker.app' in installed_applications.stdout"

- name: upgrade docker
  command:
    cmd: brew upgrade --cask docker
  when: "'Docker.app' in installed_applications.stdout"

- name: install docker font
  get_url:
    url: "{{ item }}"
    dest: /Library/Fonts
  with_items:
    - https://github.com/romkatv/dotfiles-public/raw/master/.local/share/fonts/NerdFonts/MesloLGS%20NF%20Regular.ttf
  when: not "'Docker.app' in installed_applications.stdout"

- name: Get application list 
  command:
    cmd: "ls -la /Applications/"
  register: applications

# let the user know why Docker wasn't installed
- name: assert docker is installed
  assert:
    that:
      - "'Docker.app' in applications.stdout"
    fail_msg: "Docker install failed check msg/logs"
    success_msg: "Docker installed or is already installed"

- name: reminder to start docker desktop
  debug:
    msg: "Be sure to run docker desktop app to get the cli installed and finish installation"
