---

- name: install latest neovim
  homebrew:
    name: nvim
    state: latest

- name: create nvim config dir
  file:
    path: "{{ home_dir }}/.config/nvim"
    state: directory

- name: install vim-plug
  command:
    cmd: sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'

- name: update nvim config
  template:
    src: init.vim.j2
    dest: "{{ home_dir }}/.config/nvim/init.vim"

- name: PlugInstall Reminder
  debug:
    msg: "Be sure to run PlugInstall in nvim!"
